title: RickyNite.GitHub.io
description: I am a hardware developer interested in using open-source software tools and techniques for hardware design, test automation and documentation.  
google_analytics: 
show_downloads: false
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
