title: RickyNite.GitHub.io
description: Ricky Nite is a hardware developer interested in adapting open-source software tools and techniques for hardware design, test automation and documentation.  
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
